-- Импорт перечня изданий КОКСНВО МНВО РК из «Журналы_со_ссылками.xlsx»
-- (Списки 1, 2, 3 и список журналов ВСУЗов) со ссылками на сайты журналов.
--
-- Для каждой ссылки OAI-PMH endpoint искался автоматически и проверялся вживую
-- (verb=Identify + verb=ListRecords&metadataPrefix=oai_dc) 2026-10-09. Журналы без
-- найденного OAI-PMH добавлены в реестр с crawler_type='manual' и oai_endpoint=null —
-- харвестер их пропускает, но они видны в каталоге и в фильтре КОКСНВО.
-- Дубли (один журнал в двух списках / под старым названием) схлопнуты по OAI endpoint.

-- 4 = список журналов ВСУЗов (военных и специальных учебных заведений)
alter table journals drop constraint if exists journals_koksnvo_list_check;
alter table journals add constraint journals_koksnvo_list_check check (koksnvo_list in (1, 2, 3, 4));

alter table journals add column if not exists koksnvo_included_from text;
-- Часть сайтов (Elpub/NEICON и др.) обрывает соединение для нестандартного User-Agent.
alter table journals add column if not exists oai_browser_user_agent boolean not null default false;
-- Состояние харвеста: позиция для продолжения и последняя ошибка.
alter table journals add column if not exists harvest_resumption_token text;
alter table journals add column if not exists harvest_error text;
alter table journals add column if not exists harvest_error_at timestamptz;

update journals set koksnvo_included_from = 'ақпан 2021 жыл'
where name like 'Bulletin of L.N. Gumilyov%' or name like 'Herald of Journalism%'
   or name like 'Bulletin of the Karaganda%';

insert into journals (
  name, publisher, base_url, platform, oai_endpoint, crawler_type, discipline,
  koksnvo_list, koksnvo_order, koksnvo_included_from, oai_browser_user_agent, notes
)
select v.* from (values
  ('ANAS Transactions, Earth Sciences', 'Geology and Geophysics Institute', 'https://www.journalesgia.com/en/pages/18/about-journal', null, null, 'manual', 'Жер туралы ғылымдар', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Advanced Mathematical Models and Applications', 'Jomard Publishing', 'https://jomardpublishing.com/journals/advanced-mathematical-models-applications/pages/aim-and-scope', null, null, 'manual', 'Математика', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Advances in Biology and Earth Sciences', 'Jomard Publishing', 'https://jomardpublishing.com/journals/advances-in-biology-earth-sciences/volumes', null, null, 'manual', 'Биология, жер туралы ғылымдар', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Applied and Computational Mathematics', 'Baku State University', 'https://acmij.az/', null, null, 'manual', 'Математика', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: <urlopen error [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение>).'),
  ('Avicenna Bulletin', 'Авиценна атындағы Таджик мемлекеттік медицина университеті', 'https://www.vestnik-avicenna.tj/en/', null, null, 'manual', 'Медицина ғылымдары', 1, '19.03.2025 ж. № 414 бұйрық', 'қаңтар 2025 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Azerbaijan Chemical Journal', 'Institute of Inorganic Chemistry and Catalysis', 'https://akj.az/en/', null, null, 'manual', 'Химия ғылымдары', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Azerbaijan Journal of Mathematics', 'Institute of Mathematics and Mechanics', 'https://www.azjm.org/', null, null, 'manual', 'Математика', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Azerbaijan Medical Journal', 'Azerbaijan Medical University', 'https://www.azmedjournal.com/index.php/amz', 'OJS', 'https://azmedjournal.com/index.php/amz/oai', 'oai_pmh', 'Медицина ғылымдары', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Baku State University Law Review', 'Baku State University', 'https://bsulawreview.org/?lang=en', null, null, 'manual', 'Заң ғылымдары', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Bilig', 'Қожа Ахмет Ясауи атындағы Халықаралық қазақ-түрік университеті', 'https://bilig.yesevi.edu.tr/hakkimizda.html', null, null, 'manual', 'Түркі дүниесінің гуманитарлық және әлеуметтік саласы', 1, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Bulletin of the Karaganda university - Mathematics', 'Е.А. Бөкетов атындағы Қарағанды мемлекеттік университеті', 'https://mts.buketov.edu.kz/index.php/mathematics-vestnik', 'OJS', 'https://mts.buketov.edu.kz/index.php/mathematics-vestnik/oai', 'oai_pmh', 'Математика', 1, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Bulletin of the Karaganda university - Physics', 'Е.А. Бөкетов атындағы Қарағанды мемлекеттік университеті', 'https://phs.buketov.edu.kz/index.php/physics-vestnik/index', 'OJS', 'https://phs.buketov.edu.kz/index.php/physics-vestnik/oai', 'oai_pmh', 'Физикалық ғылымдар', 1, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Chemical Problems', 'Institute of Inorganic Chemistry and Catalysis', 'https://chemprob.org/', null, null, 'manual', 'Химия ғылымдары', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Eurasian Chemico-Technological Journal', 'Жану проблемалары институты', 'https://ect-journal.kz/', 'OJS', 'https://ect-journal.kz/index.php/ectj/oai', 'oai_pmh', 'Химиялық технология, химия, материалтану, коденсияланған күй физикасы', 1, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Journal of Chemistry', 'Академик Е.А. Бөкетов атындағы Қарағанды университеті', 'https://ejc.buketov.edu.kz/ejc', 'OJS', 'https://ejc.buketov.edu.kz/index.php/ejc/oai', 'oai_pmh', 'Химиялық ғылымдар', 1, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Journal of Mathematical and Computer Applications', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://www.ejmca.org/', null, null, 'manual', 'Компьютерлік ғылымдар (бағдарламалық инженерия, желілер), математика (қолданбалы, симуляция), томография, математикалық физика (дифференциалдық және интегралдық теңдеулер, кері, корректілі емес есептер)', 1, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Eurasian Journal of Physics and Functional materials', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://ephys.kz/index.php/journal', 'OJS', 'https://ephys.kz/index.php/journal/oai', 'oai_pmh', 'Материалтану, физика және астрономия, радиация, ядролық физика және жоғарғы энергия физикасы, конденсияланған күй физикасы', 1, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Mathematical Journal', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://emj.enu.kz/index.php/main', 'OJS', 'https://emj.enu.kz/index.php/main/oai', 'oai_pmh', 'Математика', 1, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Physical Technical Journal', 'Е.А. Бөкетов атындағы Қарағанды университеті', 'https://phtj.buketov.edu.kz/index.php/EPTJ/main', 'OJS', 'https://phtj.buketov.edu.kz/index.php/EPTJ/oai', 'oai_pmh', 'Физикалық ғылымдар, материалтану, энергетика, инжиниринг', 1, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Gumilyov Journal of History', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://jhistory.enu.kz/index.php/jHistory', 'OJS', 'https://jhistory.enu.kz/index.php/jHistory/oai', 'oai_pmh', 'Археология, дүниежүзілік тарих, Отан тарихы', 1, '13.02.2026 ж. № 117 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Gumilyov Journal of Sociology', '«Л.Н.Гумилев атындағы Еуразия ұлттық университеті» КеАҚ', 'https://socjournal.enu.kz/index.php/main', 'OJS', 'https://socjournal.enu.kz/index.php/main/oai', 'oai_pmh', 'Әлеуметтану ғылымдары', 1, '19.08.2026 жылғы № 619 бұйрық', '2026 жылғы шілде айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('International journal of biology and chemistry', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://ijbch.kaznu.kz/index.php/kaznu', 'OJS', 'https://ijbch.kaznu.kz/index.php/kaznu/oai', 'oai_pmh', 'Биология және химия ғылымдары', 1, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('International journal of mathematics and physics', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://ijmph.kaznu.kz/index.php/kaznu', 'OJS', 'https://ijmph.kaznu.kz/index.php/kaznu/oai', 'oai_pmh', 'Математика және физика ғылымдары', 1, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Journal of Central Asian Studies', 'Қазақстан Республикасының Президенті жанындағы Қазақстанның стратегиялық зерттеулер институты', 'https://jcas-journal.com/index.php/jcas', 'OJS', 'https://jcas-journal.com/index.php/jcas/oai', 'oai_pmh', 'Халықаралық қатынастар', 1, '13.02.2026 ж. № 117 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Journal of Clinical Medicine of Kazakhstan', 'Ұлттық ғылыми-медицина орталығы', 'https://www.clinmedkaz.org/', null, null, 'manual', 'Медицина ғылымдары', 1, '18.02.2025 ж. № 186 бұйрық', 'қаңтар 2025 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Journal of Contemporary Applied Mathematics', 'Baku Engineering University', 'https://journalcam.com/', null, null, 'manual', 'Математика', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Khazar Journal of Humanities and Social Sciences', 'Khazar University', 'https://kjhss.khazar.org/journal/', null, null, 'manual', 'Гуманитарлық ғылымдар', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Kompleksnoe ispolzovanie mineralnogo syra', 'Сәтбаев университеті АҚ «Металлургия және кең байыту институты»', 'https://kims-imio.com/index.php/main', 'OJS', 'https://kims-imio.com/index.php/main/oai', 'oai_pmh', 'Металлургия және металлургиялық инженерия, тау-кен өндірісімен минералды өңдеу, Жер және планетааралық ғылым:жер бетіндегі процесстер', 1, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Material and mechanical engineering technology', 'Ә. Сағынов атындағы Қарағанды техникалық университеті', 'https://mmet.kstu.kz/en/post/index', null, null, 'manual', 'Материалтану, Машина жасау және мехатроника', 1, '12.07.2024 ж. № 603 бұйрық', 'шілде 2023 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('New Design Ideas', 'Jomard Publishing', 'https://jomardpublishing.com/journals/new-design-ideas', null, null, 'manual', 'Сәулет және мәдениеттану', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('New Materials, Compounds and Applications', 'Jomard Publishing', 'https://jomardpublishing.com/journals/new-materials-compounds-and-applications/current-issue', null, null, 'manual', 'Химия ғылымдары', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('News of the National Academy of Sciences of the Republic of Kazakhstan, Series of Geology and Technical Sciences', '«Орталық Азия академиялық ғылыми орталығы» ЖШС', 'https://www.geolog-technical.kz/', null, null, 'manual', 'Геология, геотехникалық инженерия және инженерлік геология', 1, '12.07.2024 ж. № 603 бұйрық, 22.10.2025 ж. № 1929', 'наурыз 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Physical Sciences and Technology', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://phst.kaznu.kz/index.php/journal/index', 'OJS', 'https://phst.kaznu.kz/index.php/journal/oai', 'oai_pmh', 'Физикалық ғылымдар', 1, '12.07.2024 ж. № 603 бұйрық', 'маусым 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Proceedings of the Institute of Mathematics and Mechanics', 'Institute of Mathematics and Mechanics', 'https://proc.imm.az/', null, null, 'manual', 'Математика', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Processes of Petrochemistry and Oil Refining', 'Academician Y.H. Mammadaliyev Institute of Petrochemical Processes', 'https://ppor.az/', 'OJS', 'https://ppor.az/index.php/ppor/oai', 'oai_pmh', 'Химия ғылымдары', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('SOCAR Proceedings', 'Oil Gas Scientific Research Project Institute', 'https://proceedings.socar.az/ru/home', null, null, 'manual', 'Техникалық ғылымдар', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('TWMS Journal of Pure and Applied Mathematics', 'Baku State University', 'https://twmsj.az/Index.aspx', null, null, 'manual', 'Математика', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Transactions of National Academy of Sciences of Azerbaijan. Series of Physical-Technical and Mathematical Sciences', 'Institute of Mathematics and Mechanics', 'https://trans.imm.az/', null, null, 'manual', 'Математика', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('UNEC Journal of Engineering and Applied Sciences', 'Azerbaijan State University of Economics (UNEC)', 'https://unec-jeas.com/', null, null, 'manual', 'Техникалық ғылымдар', 1, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Микробиология және вирусология', '«Микробиология және вирусология ғылыми-өндірістік орталығы» Жауапкершілігі шектеулі серіктестігі', 'https://www.imv-journal.kz/index.php/mav/issue/view/24', 'OJS', 'https://imv-journal.kz/index.php/mav/oai', 'oai_pmh', 'Биология ғылымдары', 1, '02.06.2026 ж. № 296 бұйрық', '2026 жылғы шілде айынан бастап', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Репродуктивті медицина', 'Қазақстан репродуктивтік медицина қауымдастығы', 'https://repromed.kz/index.php/journal/index', 'OJS', 'https://repromed.kz/index.php/journal/oai', 'oai_pmh', 'Медицина', 1, '28.02.2025 ж. № 302 бұйрық', 'қаңтар 2025 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Экономика: стратегия және практика', 'Қазақстан Республикасы Ғылым және жоғары білім министрлігі Ғылым комитетінің «Экономика институты»', 'https://esp.ieconom.kz/jour', 'Elpub', 'https://esp.ieconom.kz/jour/oai', 'oai_pmh', 'Экономика ғылымдары', 1, '24.10.2025 ж. № 1975 бұйрық', '2025 жылғы қазан айынан бастап', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Қазақстан археологиясы', 'Қазақстан Республикасы Білім және ғылым министрлігі Ғылым комитетінің Ә.Х. Марғұлан атындағы Археология институты', 'https://archeo.kz/ru/page-zhurnal-azastan-arheologiyasy/', null, null, 'manual', 'Тарих ғылымдары', 1, '12.07.2024 ж. № 603 бұйрық', 'қазан 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қазақстан-Британ техникалық университетінің хабаршысы - Herald of the Kazakh British Technical University', 'Қазақстан-Британ техникалық университеті', 'https://vestnik.kbtu.edu.kz/jour?locale=en_US', 'Elpub', 'https://vestnik.kbtu.edu.kz/jour/oai', 'oai_pmh', 'Физикалық ғылымдар, компьютерлік ғылымдар, математика ғылымдары, Мұнай-газ инженерия және геология', 1, '18.04.2026 ж. № 281 бұйрық', '2026 жылғы қаңтар айынан бастап', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('ҚазҰУ хабаршысы. Математика, механика, информатика сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bm.kaznu.kz/index.php/kaznu/kk/index', 'OJS', 'https://bm.kaznu.kz/index.php/kaznu/oai', 'oai_pmh', 'Математика, механика, информатика', 1, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Физика сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bph.kaznu.kz/index.php/zhuzhu/kk/about', 'OJS', 'https://bph.kaznu.kz/index.php/zhuzhu/oai', 'oai_pmh', 'Физикалық ғылымдары', 1, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Химия сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-chemistry.kaznu.kz/index.php/kaznu/kk', 'OJS', 'https://bulletin-chemistry.kaznu.kz/index.php/kaznu/oai', 'oai_pmh', 'Химиялық ғылымдар', 1, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('3i: intellect, idea, innovation – интеллект, идея, инновация', 'А.Байтұрсынов атындағы Қостанай өңірлік университеті', 'https://ojs.ksu.edu.kz/index.php/3i/index', 'OJS', 'https://ojs.ksu.edu.kz/index.php/3i/oai', 'oai_pmh', 'Ауыл шаруашылығы және ветеринария ғылымдары бойынша', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Academic Journal of Physical and Chemical Sciences (бұрыңғы атауы - ҚР ҰҒА Баяндамалары)', '«Орталық Азия академиялық ғылыми орталығы» ЖШС', 'https://journals.nauka-nanrk.kz/reports-science/about', 'OJS', 'https://journals.nauka-nanrk.kz/reports-science/oai', 'oai_pmh', 'Физика және химия ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық, 22.10.2025 ж. № 1929 бұйрық', 'сәуір 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Academic Scientific Journal of Chemistry (бұрыңғы атауы-Қазақстан Республикасының Ұлттық ғылым академиясының хабарлары. Химия және технология сериясы)', '«Орталық Азия академиялық ғылыми орталығы» ЖШС', 'https://journals.nauka-nanrk.kz/chemistry-technology/about', 'OJS', 'https://journals.nauka-nanrk.kz/chemistry-technology/oai', 'oai_pmh', 'Химия ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық, 22.10.2025 ж. № 1929 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Academic Scientific Journal of Computer Science Қазақстан (бұрыңғы атауы - Қазақстан Республикасының Ұлттық ғылым академиясының хабарлары. Физика-математика сериясы)', '«Орталық Азия академиялық ғылыми орталығы» ЖШС', 'https://journals.nauka-nanrk.kz/physics-mathematics/about', 'OJS', 'https://journals.nauka-nanrk.kz/physics-mathematics/oai', 'oai_pmh', 'Ақпараттық-коммуникациялық технологиялар', 2, '12.07.2024 ж. № 603 бұйрық, 22.10.2025 ж. № 1929 бұйрық', 'мамыр 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Agricultural Systems and Natural Resources (бұрыңғы атауы -Ғылым және білім)', 'Жәңгір хан атындағы Батыс Қазақстан аграрлық-техникалық университеті', 'https://crop.wkau.kz/index.php/asnr/en/index', 'OJS', 'https://crop.wkau.kz/index.php/asnr/oai', 'oai_pmh', 'Ауыл шаруашылығы ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 23.04.2026 ж. № 301 бұйрық', '2021 жылғы қыркүйек айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Animal Health and Biosafety (бұрыңғы атауы - Ғылым және білім)', 'Жәңгір хан атындағы Батыс Қазақстан аграрлық-техникалық университеті', 'https://vet.wkau.kz/index.php/ahb/en', 'OJS', 'https://vet.wkau.kz/index.php/ahb/oai', 'oai_pmh', 'Ветеринария ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 23.04.2026 ж. № 301 бұйрық', '2021 жылғы қыркүйек айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Animal Husbandry and Aquaculture (бұрыңғы атауы -Ғылым және білім)', 'Жәңгір хан атындағы Батыс Қазақстан аграрлық-техникалық университеті', 'https://ahf.wkau.kz/', 'OJS', 'https://ahf.wkau.kz/index.php/ahf/oai', 'oai_pmh', 'Ауыл шаруашылығы ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 23.04.2026 ж. № 301 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Applied Agro Engineering (бұрыңғы атауы - Ғылым және білім)', 'Жәңгір хан атындағы Батыс Қазақстан аграрлық-техникалық университеті', 'https://agrotech.wkau.kz/index.php/aae/en/index', 'OJS', 'https://agrotech.wkau.kz/index.php/aae/oai', 'oai_pmh', 'Ауыл шаруашылығы ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 23.04.2026 ж. № 301 бұйрық', '2021 жылғы қыркүйек айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Arts Academy', 'Қазақ ұлттық хореография академиясы', 'https://artsacademy.kz/index.php/main', 'OJS', 'https://artsacademy.kz/index.php/main/oai', 'oai_pmh', 'Өнертану, хореография, театр, арт-менеджмент', 2, '02.03.2026 г. № 46 бұйрық', '2025 жылғы қазан айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Asian Journal "Steppe Panorama"', 'Ш.Ш. Уәлиханов атындағы Тарих және этнология институты', 'https://ajspiie.com/index.php/history/about', 'OJS', 'https://ajspiie.com/index.php/history/oai', 'oai_pmh', 'Тарих ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Buketov Business Review (бұрыңғы атауы Қарағанды университетінің хабаршысы. Серия экономика)', 'Академик Е.А. Бөкетов атындағы Қарағанды университеті', 'https://bbr.buketov.edu.kz/', 'OJS', 'https://bbr.buketov.edu.kz/index.php/economy-vestnik/oai', 'oai_pmh', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 17.03.2025 ж. № 412', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Bulletin of the International University of Tourism and Hospitality', 'Халықаралық туризм және меймандостық университеті', 'https://journal.iuth.edu.kz/index.php/main', 'OJS', 'https://journal.iuth.edu.kz/index.php/main/oai', 'oai_pmh', 'Туризм', 2, '19.09.2025 ж. №1605 бұйрық', '2025 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Central Asian Journal of Art Studies', 'Т.Қ. Жүргенов ат. Қазақ ұлттық өнер академиясы', 'https://www.cajas.kz/journal', 'OJS', 'https://www.cajas.kz/journal/oai', 'oai_pmh', 'Өнертану', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Central Asian Journal of Medical Hypotheses and Ethics', 'Оңтүстік Қазақстан медицина академиясы', 'https://cajmhe.com/', 'OJS', 'https://cajmhe.com/index.php/journal/oai', 'oai_pmh', 'Медицина', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Central Asian Journal of Veterinary Science (бұрыңғы атауы - Herald of Science of Seifullin Kazakh Agro Technical Research University:Veterinary Science)', 'С.Сейфуллин атындағы Қазақ агротехникалық зерттеу университеті', 'https://bulletinofscience.kazatu.edu.kz/index.php/veterinary-science/issue/archive', 'OJS', 'https://bulletinofscience.kazatu.edu.kz/index.php/veterinary-science/oai', 'oai_pmh', 'Ветеринария ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 04.09.2024 ж. № 800 бұйрық 19.02.2026 ж. № 125 бұйрық', '2021 жылғы қыркүйек айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Central Asian Journal of water research', 'Қазақстан-Неміс университеті', 'https://cajwr.scholasticahq.com/', null, null, 'manual', 'Биология және су ресурстары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Central Asian Transactions on Materials Structure and Properties (бұрыңғы атауы - Д.Серікбаев атындағы Шығыс Қазақстан техникалық университетінің Хабаршысы)', 'Д.Серікбаев атындағы Шығыс Қазақстан техникалық университеті', 'https://journals.ektu.kz/catmsp/search', 'OJS', 'https://journals.ektu.kz/catmsp/oai', 'oai_pmh', 'Инженерия және инженерлік іс', 2, '12.07.2024 ж. № 603 бұйрық, 18.04.2026 ж. № 282 бұйрық', 'наурыз 2022 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Central Asian economic review', 'Нархоз Университеті', 'https://caer.narxoz.kz/index/index?locale=en_US', 'OJS', 'https://caer.narxoz.kz/index/oai', 'oai_pmh', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('DentistKazakhstan', '«Қазақстан стоматологиясының ассоциациясы» қоғамдық бірлестігі', 'https://dentistrykazakhstan.kz/', null, null, 'manual', 'Стоматология және жақ-бет хирургиясы', 2, '17.03.2026 ж. № 172 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('EKTU journal of Architectural and Construction Sciences (бұрыңғы атауы – Д.Серікбаев атындағы Шығыс Қазақстан техникалық университетінің Хабаршысы)', 'Д.Серікбаев атындағы Шығыс Қазақстан техникалық университеті', 'https://journals.ektu.kz/jacs', 'OJS', 'https://journals.ektu.kz/jacs/oai', 'oai_pmh', 'Сәулет және құрылыс', 2, '12.07.2024 ж. № 603 бұйрық, 18.04.2026 ж. № 282 бұйрық', '2022 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('EKTU journal of Engineering Sciences (бұрыңғы атауы – Д.Серікбаев атындағы Шығыс Қазақстан техникалық университетінің Хабаршысы)', 'Д.Серікбаев атындағы Шығыс Қазақстан техникалық университеті', 'https://journals.ektu.kz/jes', 'OJS', 'https://journals.ektu.kz/jes/oai', 'oai_pmh', 'Инженерия және инженерлік іс', 2, '12.07.2024 ж. № 603 бұйрық, 18.04.2026 ж. № 282 бұйрық', '2022 жылғы наурыз айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('EKTU journal of Information and Communication Sciences (бұрыңғы атауы – Д.Серікбаев атындағы Шығыс Қазақстан техникалық университетінің Хабаршысы)', 'Д.Серікбаев атындағы Шығыс Қазақстан техникалық университеті', 'https://journals.ektu.kz/jics', 'OJS', 'https://journals.ektu.kz/jics/oai', 'oai_pmh', 'Ақпараттық және коммуникациялық технологиялар', 2, '12.07.2024 ж. № 603 бұйрық, 18.04.2026 ж. № 282 бұйрық', '2022 жылғы наурыз айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Education. Quality Assurance', 'Аккредиттеу және рейтингтің тәуелсіз агенттігі', 'https://iaar-education.kz/', null, null, 'manual', 'Экономика', 2, '12.07.2024 ж. № 603 бұйрық', '2024 жылғы қаңтар айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Engineering journal of Satbayev University', 'Қ.И. Сатпаев атындағы Қазақ ұлттық техникалық зерттеу университеті', 'https://vestnik.satbayev.university/', 'OJS', 'https://vestnik.satbayev.university/index.php/journal/oai', 'oai_pmh', 'Металлургия', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Journal of Applied Biotechnology', 'Ұлттық биотехнология орталығы', 'https://biotechlink.org/index.php/journal/about', 'OJS', 'https://biotechlink.org/index.php/journal/oai', 'oai_pmh', 'Биотехнология', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2022 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Journal of Applied Engineering and Technology', 'Л.Н.Гумилев атындағы Еуразия ұлттық университеті', 'https://ejaet.enu.kz/index.php/main', 'OJS', 'https://ejaet.enu.kz/index.php/main/oai', 'oai_pmh', 'Машина жасау, көлік, геосинтетикалық материалдар', 2, '12.07.2024 ж. № 603 бұйрық 14.08.2026 ж. № 600 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Journal of Current Research in Psychology and Pedagogy', '«Тұран» Университеті', 'https://ejcrpp.turan-edu.kz/jour?locale=en_US', 'Elpub', 'https://ejcrpp.turan-edu.kz/jour/oai', 'oai_pmh', 'Қолданбалы психология және зерттеулер, жалпы және әлеуметтік психология', 2, '18.04.2026 ж. № 282 бұйрық', '2026 жылғы наурыз айынан бастап', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Eurasian Journal of Economic and Business Studies (EJEBS)', 'Қ.Сағадиев атындағы Халықаралық Бизнес университеті', 'https://ejebs.uib.kz/jour?locale=en_US', 'Elpub', 'https://ejebs.uib.kz/jour/oai', 'oai_pmh', 'Экономика және туризм салалары', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2022 жыл', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Eurasian Journal of Gender Studies', 'Кенжеғали Сағадиев атындағы Халықаралық Бизнес Университеті', 'https://ejgs.kz/index.php/main', 'OJS', 'https://ejgs.kz/index.php/main/oai', 'oai_pmh', 'Бизнес және басқару', 2, '10.06.2026 ж. №426 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Journal of History (бұрыңғы атауы - Қарағанды университетінің хабаршысы. Тарих. Философия сериясы)', 'Академик Е.А. Бөкетов атындағы Қарағанды университеті', 'https://ejh.buketov.edu.kz/', 'OJS', 'https://ejh.buketov.edu.kz/index.php/index/oai', 'oai_pmh', 'Тарих және философия ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық, 18.04.2026 ж. № 282 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian Journal of International Law (EAJIL)', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://eajil.enu.kz/index.php/main', 'OJS', 'https://eajil.enu.kz/index.php/main/oai', 'oai_pmh', 'Құқық', 2, '04.06.2026 ж. № 402 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Eurasian research journal', 'Қожа Ахмет Ясауи атындағы Халықаралық Қазақ-Түрік университеті', 'https://erj.eurasian-research.org/journal-information.html', null, null, 'manual', 'Экономика ғылымдары', 2, '06.08.2024 ж. № 694 бұйрық', '2024 жылғы қаңтар айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Fundamental and Experimental Biology (бұрыңғы атауы "Қарағанды университетінің хабаршысы. Биология, медицина, география сериясы"', 'Академик Е.А. Бөкетов атындағы Қарағанды университеті', 'https://feb.buketov.edu.kz/', 'OJS', 'https://feb.buketov.edu.kz/index.php/index/oai', 'oai_pmh', 'Биологиялық ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Gumilyov Journal of Pedagogy (бұрыңғы атауы Л.Н. Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Педагогика. Психология. Әлеуметтану сериясы)', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://pedjournal.enu.kz/index.php/main-about', 'OJS', 'https://pedjournal.enu.kz/index.php/main-about/oai', 'oai_pmh', 'Педагогика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 06.05.2025 ж. № 685 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('International Journal of Economics and Project Management', 'Institute of Economics and Project Management', 'https://ijepm.com/index.php/ijepm', 'OJS', 'https://ijepm.com/index.php/ijepm/oai', 'oai_pmh', 'Экономика, менеджмент', 2, '10.06.2026 ж. №426 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Jete – Journal of philosophy, religios and cultural studies (бұрыңғы атауы - Л.Н.Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Тарихи ғылымдар. Философия. Дінтану сериясы)', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://jete.enu.kz/index.php/bastybet', 'OJS', 'https://jete.enu.kz/index.php/bastybet/oai', 'oai_pmh', 'Философия', 2, '12.07.2024 ж. № 603 бұйрық 06.05.2025 ж. № 685 бұйрық', 'қазан 2022 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Journal of Health Development', 'Қазақстан Республикасы Денсаулық сақтау министрлігінің Салидат Қайырбекова атындағы Денсаулық сақтауды дамыту ұлттық ғылыми орталығы', 'https://jhdkz.org/gallery/Special%20issue.%20Number%2040%20%282021%29.pdf', 'OJS', 'https://jhdkz.org/index.php/index/oai', 'oai_pmh', 'Медицина', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2022 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Journal of Problems in Computer Science and Information Technologies', 'Әл-Фараби атындағы Қазақ ұлттық университеті', 'https://jpcsit.kaznu.kz/index.php/kaznu/en/issue/archive', 'OJS', 'https://jpcsit.kaznu.kz/index.php/kaznu/oai', 'oai_pmh', 'Компьютерлік ғылымдар және ақпараттық технологиялар', 2, '20.12.2024 ж. № 1204 бұйрық', '2025 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Kazakh Mathematical Journal', 'Математика және математикалық модельдеу институты', 'https://mathjournal.kz/index.php/kmj/about', 'OJS', 'https://mathjournal.kz/index.php/kmj/oai', 'oai_pmh', 'Математика', 2, '04.06.2026 ж. № 402 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09. OAI Identify работает, ListRecords возвращает HTTP 500 (проверено 2026-10-09).'),
  ('Logos: Eurasian Journal of Philosophy (бұрыңғы атауы - Қарағанды университетінің хабаршысы. Тарих. Философия сериясы)', 'Академик Е.А. Бөкетов атындағы Қарағанды ұлттық зерттеу университеті', 'https://lejph.buketov.edu.kz/', null, null, 'manual', 'Философия ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық, 18.04.2026 ж. № 282 бұйрық', '2021 жылғы наурыз айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09. OAI на этом домене отдаёт репозиторий другого журнала (ejh.buketov.edu.kz).'),
  ('Psychology and cognitive sciences (бұрыңғы атауы - Л.Н. Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Педагогика. Психология. Әлеуметтану сериясы)', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://psyjournal.enu.kz/index.php/pcs-journal/about', 'OJS', 'https://psyjournal.enu.kz/index.php/pcs-journal/oai', 'oai_pmh', 'Психология', 2, '12.07.2024 ж. № 603 бұйрық 06.05.2025 ж. № 685 бұйрық', '2021 жылғы наурыз айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Qainar Journal of Social Science', '«Q» University', 'https://q-university.edu.kz/en/science/journal', null, null, 'manual', 'Әлеуметтік экономика, демография, адами ресурстар және еңбек нарығы', 2, '13.02.2026 ж. № 117 бұйрық', '2026 жылғы наурыз айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('SDU University Хабаршысы: педагогика және оқыту әдістемесі» -SDU University Bulletin: Pedagogy and teaching methods - Вестник SDU University: педагогика и методы обучения', 'SDU University', 'https://ptm.sdu.edu.kz/index.php/ptm/about', 'OJS', 'https://ptm.sdu.edu.kz/index.php/ptm/oai', 'oai_pmh', 'Білім беру теориясы мен практикасы, STEM-білім беру, білім беру саласындағы әкімшілендіру, цифрлық білім беру', 2, '13.02.2026 ж. № 117 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Saryn', 'Құрманғазы атындағы Қазақ ұлттық консерваториясы', 'https://sarynjournal.kz/saryn', 'OJS', 'https://sarynjournal.kz/index.php/saryn/oai', 'oai_pmh', 'Өнер және гуманитарлық ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'шілде 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Scientific Journal of Astana IT University', '«Astana IT University»', 'https://journal.astanait.edu.kz/index.php/ojs', 'OJS', 'https://journal.astanait.edu.kz/index.php/ojs/oai', 'oai_pmh', 'Ақпараттық және коммуникациялық технологиялар', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2022 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Scientific Journal of Pedagogy and Economics (бұрыңғы атауы - Қазақстан Республикасының Ұлттық ғылым академиясының хабаршысы)', '«Орталық Азия академиялық ғылыми орталығы» ЖШС', 'https://journals.nauka-nanrk.kz/bulletin-science/about', 'OJS', 'https://journals.nauka-nanrk.kz/bulletin-science/oai', 'oai_pmh', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық, 22.10.2025 ж. № 1929 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('TILTANYM', 'Ахмет Байтұрсынұлы атындағы Тіл білімі институты', 'https://tbi.kz/page39623913.html', null, null, 'manual', 'Филология', 2, '12.07.2024 ж. № 603 бұйрық', 'шілде 2022 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Technobius', '«Technobius» ЖШС', 'https://technobius.kz/index.php/tech', 'OJS', 'https://technobius.kz/index.php/tech/oai', 'oai_pmh', 'Құрылыс, материалтану', 2, '12.07.2024 ж. № 603 бұйрық', '2024 жылғы сәуір айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Traumatology and Orthopaedics of Kazakhstan', 'Академик Н.Ж.Батпенов атындағы Ұлттық ғылыми Травматология және ортопедия орталығы', 'https://www.journaltokaz.org/index.php/tok/about', 'OJS', 'https://www.journaltokaz.org/index.php/tok/oai', 'oai_pmh', 'Медицина ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Turkic Studies Journal', 'Л.Н.Гумилев атындағы Еуразия ұлттық университеті', 'https://tsj.enu.kz/index.php/new/index', 'OJS', 'https://tsj.enu.kz/index.php/new/oai', 'oai_pmh', 'Филология ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('West Kazakhstan Medical Journal', 'Марат Оспанов атындағы Батыс Қазақстан медицина университеті', 'https://journal.zkgmu.kz/ru/', null, null, 'manual', 'Денсаулық туралы ғылым', 2, '12.07.2024 ж. № 603 бұйрық', '2024 жылғы қаңтар айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Yassawi Journal of Education Studies (бұрыңғы атауы - Ясауи университетінің хабаршысы)', 'Қожа Ахмет Ясауи атындағы Халықаралық қазақ-түрік университеті', 'https://publications.ayu.edu.kz/index.php/yjes/index', 'OJS', 'https://publications.ayu.edu.kz/index.php/yjes/oai', 'oai_pmh', 'Педагогика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 09.02.2026 № 51 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Yassawi Journal of Philology (бұрыңғы атауы - Ясауи университетінің хабаршысы)', 'Қожа Ахмет Ясауи атындағы Халықаралық қазақ -түрік университеті', 'https://publications.ayu.edu.kz/index.php/yjph/index', 'OJS', 'https://publications.ayu.edu.kz/index.php/yjph/oai', 'oai_pmh', 'Филология ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 09.02.2026 № 51 бұйрық', '2021 жылғы желтоқсан айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('«Тұран» университеті', 'Eurasian scientific journal of law', 'https://turan.edu.kz/ru/science/scientific-publications-of-the-university', null, null, 'manual', 'Құқық', 2, '05.06.2025 ж. №893 бұйрық', '2024 жылғы қаңтар айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('«Тұран» университетінің хабаршысы', '«Тұран» университеті', 'https://vestnik.turan-edu.kz/jour?locale=kk_KZ', 'Elpub', 'https://vestnik.turan-edu.kz/jour/oai', 'oai_pmh', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'мамыр 2021 жыл', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Ізденістер, Нәтижелер', 'Қазақ Ұлттық Аграрлық Зерттеу университеті', 'https://journal.kaznaru.edu.kz/index.php/research/about', 'OJS', 'https://journal.kaznaru.edu.kz/index.php/research/oai', 'oai_pmh', 'Ауыл шаруашылығы ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абай атындағы Қазақ ұлттық педагогикалық университетінің Хабаршысы. Педагогика ғылымдары сериясы', 'Абай атындағы Қазақ ұлттық педагогикалық университеті', 'https://bulletin-pedagogy.kaznpu.kz/index.php/ped', 'OJS', 'https://bulletin-pedagogy.kaznpu.kz/index.php/ped/oai', 'oai_pmh', 'Педагогика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абай атындағы Қазақ ұлттық педагогикалық университетінің Хабаршысы. Психология сериясы', 'Абай атындағы Қазақ ұлттық педагогикалық университеті', 'https://bulletin-psychology.kaznpu.kz/index.php/ped/index', 'OJS', 'https://bulletin-psychology.kaznpu.kz/index.php/ped/oai', 'oai_pmh', 'Психология ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абай атындағы Қазақ ұлттық педагогикалық университетінің Хабаршысы. Тарих және әлеуметтік-саяси ғылымдар сериясы', 'Абай атындағы Қазақ ұлттық педагогикалық университеті', 'https://bulletin-histsocpolit.kaznpu.kz/index.php/ped/index', 'OJS', 'https://bulletin-histsocpolit.kaznpu.kz/index.php/ped/oai', 'oai_pmh', 'Тарих ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абай атындағы Қазақ ұлттық педагогикалық университетінің Хабаршысы. Физика-математика ғылымдары сериясы', 'Абай атындағы Қазақ ұлттық педагогикалық университеті', 'https://bulletin-phmath.kaznpu.kz/index.php/ped/index', 'OJS', 'https://bulletin-phmath.kaznpu.kz/index.php/index/oai', 'oai_pmh', 'Ақпараттық-коммуникациялық технологиялар', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абай атындағы Қазақ ұлттық педагогикалық университетінің хабаршысы. Әлеуметтану және саяси ғылымдары', 'Абай атындағы Қазақ ұлттық педагогикалық университеті', 'https://bulletin-socpolit.kaznpu.kz/index.php/ped/Journal-policy', 'OJS', 'https://bulletin-socpolit.kaznpu.kz/index.php/ped/oai', 'oai_pmh', 'Саяси ғылымдар', 2, '22.10.2024 ж. № 900 бұйрық', '2024 жылғы қазан айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абылай хан атындағы ҚазХҚ және ӘТУ хабаршысы. Педагогика ғылымдары сериясы', 'Абылай хан атындағы халықаралық қатынастар және әлем тілдері университеті', 'https://bulletin-pedagogical.ablaikhan.kz/index.php/j1', 'OJS', 'https://bulletin-pedagogical.ablaikhan.kz/index.php/j1/oai', 'oai_pmh', 'Педагогика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абылай хан атындағы ҚазХҚ және ӘТУ хабаршысы. Филология ғылымдары сериясы', 'Абылай хан атындағы халықаралық қатынастар және әлем тілдері университеті', 'https://bulletin-philology.ablaikhan.kz/index.php/j1/index', 'OJS', 'https://bulletin-philology.ablaikhan.kz/index.php/j1/oai', 'oai_pmh', 'Филология ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абылай хан атындағы ҚазХҚ және ӘТУ хабаршысы. Халықаралық қатынастар және аймақтану сериясы', 'Абылай хан атындағы халықаралық қатынастар және әлем тілдері университеті', 'https://bulletin-irr.ablaikhan.kz/index.php/j1', 'OJS', 'https://bulletin-irr.ablaikhan.kz/index.php/j1/oai', 'oai_pmh', 'Халықаралық қатынастар және аймақтану', 2, '12.07.2024 ж. № 603 бұйрық', 'сәуір 2022 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Адам әлемі', 'Философия, саясаттану және дінтану институты', 'https://adamalemijournal.com/index.php/aa/index', 'OJS', 'https://adamalemijournal.com/index.php/aa/oai', 'oai_pmh', 'Философия ғылымдары (оның ішінде мәдениет философиясы, дін философиясы)', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Азаматтық авиация академиясының жаршысы', 'Азаматтық авиация академиясы', 'https://caa.edu.kz/vestnik-akademii-grazhdanskoy-aviacii-228', null, null, 'manual', 'Компьютерлік ғылымдар және информатика', 2, '10.01.2025 ж. № 1 бұйрық', '2025 жылғы қаңтар айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Алматы технологиялық университетінің хабаршысы', 'Алматы технологиялық университеті', 'https://www.vestnik-atu.kz/jour?locale=ru_RU', 'Elpub', 'https://www.vestnik-atu.kz/jour/oai', 'oai_pmh', 'Женіл және қайта өңдеу өндірісі', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Алматы энергетика және байланыс университетінің хабаршысы', 'Ғұмарбек Дәукеев атындағы Алматы энергетика және байланыс университеті', 'https://vestnik.aues.kz/', 'OJS', 'https://vestnik.aues.kz/index.php/none/oai', 'oai_pmh', 'Энергетика және энергетикалық машина жасау; ақпараттық, телекоммуникациялық және ғарыштық технологиялар', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Алынып тасталды Қазақстан фармациясы', 'Қазақстан Республикасы Денсаулық сақтау министрлігі медициналық және фармацевтикалық бақылау комитетінің Дәрілік заттар мен медициналық мақсаттағы бұйымдарды сараптау ұлттық орталығы', 'https://pharmkaz.kz/', null, null, 'manual', 'Медицина, Фармация', 2, '12.07.2024 ж. № 603 бұйрық, алынып тасталды 05.03.2025 жылғы № 324 бұйрық', 'қараша 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: HTTP 503).'),
  ('Астана медициналық журналы', '«Астана» Медицина университеті', 'https://medical-journal.kz/index.php/mua/about_journal', 'OJS', 'https://medical-journal.kz/index.php/mua/oai', 'oai_pmh', 'Медицина ғылымдары', 2, '05.08.2024 ж. № 673 бұйрық', '2024 жылғы шілде айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Ашық жүйелер эволюциясының мәселелері журналы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://peos.kaznu.kz/index.php/peos/kk/issue/archive', 'OJS', 'https://peos.kaznu.kz/index.php/peos/oai', 'oai_pmh', 'Физика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'шілде 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Білім-образование', 'Ы. Алтынсарин атындағы Ұлттық білім академиясы', 'https://bilim-uba.kz/index.php/science', 'OJS', 'https://bilim-uba.kz/index.php/science/oai', 'oai_pmh', 'Педагогикалық ғылымдар бағыты', 2, '12.07.2024 ж. № 603 бұйрық', '2024 жылғы шілде айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('География және су ресурстары', 'География және су қауіпсіздігі институты', 'https://ojs.ingeo.kz/index.php/givr/index', null, null, 'manual', 'География және су ресурстары', 2, '12.07.2024 ж. № 603 бұйрық', 'сәуір 2023 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: <urlopen error timed out>).'),
  ('Гидрометеорология және экология', 'ШЖҚ РМК «ҚазГидроМет»', 'https://journal.kazhydromet.kz/kazgidro/index', 'OJS', 'https://journal.kazhydromet.kz/index.php/kazgidro/oai', 'oai_pmh', 'Жер туралы ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Горение и плазмохимия', 'Жану проблемалары институты', 'https://icp.kz/magazine/', null, null, 'manual', 'Жану және плазмохимия, жарылғыш заттар және пиротехникалық материалдар технологиясы, химиялық физика, материалтану, нанотехнологиялар', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Дене тәрбиесінің теориясы мен әдістемесі', 'Қазақ спорт және туризм академиясы', 'https://tmfk.kz/', null, null, 'manual', 'Педагогика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: HTTP 404).'),
  ('Еуразия гуманитарлық институтының хабаршысы', 'А.Құсайынов атындағы Еуразия гуманитарлық институты', 'https://ojs.egi.kz/index.php/BULLETIN', 'OJS', 'https://ojs.egi.kz/index.php/BULLETIN/oai', 'oai_pmh', 'Филология ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2022 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09. OAI Identify работает, ListRecords возвращает HTTP 500 (проверено 2026-10-09).'),
  ('Еуразиялық агротехникалық журнал/Eurasian agrotechnical journal/ Евразийский агротехнический журнал (бұрыңғы атауы - С.Сейфуллин атындағы Қазақ агротехникалық зерттеу университетінің ғылым жаршысы: Пәнаралық)', 'С.Сейфуллин атындағы Қазақ агротехникалық зерттеу университеті', 'https://bulletinofscience.kazatu.edu.kz/index.php/bulletinofscience/index', 'OJS', 'https://bulletinofscience.kazatu.edu.kz/index.php/bulletinofscience/oai', 'oai_pmh', 'Ауылшаруашылық ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 19.02.2026 ж. № 125 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Керуен', 'М.О. Әуезов атындағы Әдебиет және өнер институты', 'https://keruenjournal.kz/', 'OJS', 'https://keruenjournal.kz/main/oai', 'oai_pmh', 'Әдебиеттану, өнертану', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Л.Н. Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Саяси ғылымдар, аймақтану, шығыстану, түркітану сериясы', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://bulpolit.enu.kz/index.php/main', 'OJS', 'https://bulpolit.enu.kz/index.php/main/oai', 'oai_pmh', 'Саяси ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Л.Н. Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Физика. Астрономия сериясы', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://bulphysast.enu.kz/index.php/physast', 'OJS', 'https://bulphysast.enu.kz/index.php/physast/oai', 'oai_pmh', 'Физика ғылымдары', 2, '23.07.2024 ж. № 645 бұйрық', '2024 жылғы шілде айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Л.Н. Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Химия. География сериясы', 'Л.Н. Гумилев атындағы Еуразия ұлттық университет', 'https://bulchmed.enu.kz/index.php/bulchmed', 'OJS', 'https://bulchmed.enu.kz/index.php/bulchmed/oai', 'oai_pmh', 'Химия ғылымдары', 2, '10.02.2025 ж. № 122 бұйрық, 13.02.2026 ж. № 117 бұйрық', '2024 жылғы қазан айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Л.Н. Гумилев атындағы ЕҰУ хабаршысының экономика сериясы', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://bulecon.enu.kz/index.php/main/', 'OJS', 'https://bulecon.enu.kz/index.php/main/oai', 'oai_pmh', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09. OAI Identify работает, ListRecords возвращает HTTP 500 (проверено 2026-10-09).'),
  ('Л.Н.Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Биологиялық ғылымдар сериясы', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://bulbio.enu.kz/index.php/main', 'OJS', 'https://bulbio.enu.kz/index.php/main/oai', 'oai_pmh', 'Биологиялық ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Л.Н.Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Журналистика сериясы', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://buljourn.enu.kz/index.php/main', 'OJS', 'https://buljourn.enu.kz/index.php/main/oai', 'oai_pmh', 'Журналистика', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Л.Н.Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Математика, компьютерлік ғылымдар, механика сериясы', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://bulmathmc.enu.kz/index.php/main', 'OJS', 'https://bulmathmc.enu.kz/index.php/main/oai', 'oai_pmh', 'Математика, компьютерлік ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Л.Н.Гумилев атындағы Еуразия ұлттық университетінің хабаршысы. Құқық сериясы', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://bullaw.enu.kz/index.php/main/index', 'OJS', 'https://bullaw.enu.kz/index.php/main/oai', 'oai_pmh', 'Құқық', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('М.Тынышбаев атындағы Қазақ көлік және коммуникациялар академиясының Хабаршысы', 'Логистика және көлік академиясы', 'https://vestnik.alt.edu.kz/index.php/journal/issue/download/69/74', 'OJS', 'https://vestnik.alt.edu.kz/index.php/journal/oai', 'oai_pmh', 'Көлік, көлік инженериясы, көлік логистикасы, жүк тасуды ұйымдастыру, автоматтандыру, телемеханика, байланыс, энергетика', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Медицина және экология', 'Қарағанды медицина университеті', 'https://qmu.edu.kz/ru/nauka/zhurnal/', null, null, 'manual', 'Медицина', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2024 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Мемлекеттік аудит-Государственный аудит', 'Зерттеулер,талдау және тиімділікті бағалау орталығы', 'https://gov-audit.kz/index.php/ma', 'OJS', 'https://gov-audit.kz/index.php/ma/oai', 'oai_pmh', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Мемлекеттік басқару және мемлекеттік қызмет Халықаралық ғылыми-талдау журналы', 'Қазақстан Республикасы Президентінің жанындағы Мемлекеттік басқару академиясы', 'https://journal.apa.kz/index.php/path', 'OJS', 'https://journal.apa.kz/index.php/path/oai', 'oai_pmh', 'Халықаралық қатынастар', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Механика және технологиялар', 'М.Х. Дулати атындағы Тараз өңірлік университеті', 'https://journals.dulaty.kz/ru/', null, null, 'manual', 'Құрылыс технология, жеңіл өнеркәсіп технологиясы, химиялық технологиялар, тамақ өнімдерінің технологиясы', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2024 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: <urlopen error timed out>).'),
  ('Мәдени мұра', 'Қазақстан Республикасының Ұлттық музейі', 'https://madenimura-journal.kz/index.php/main', 'OJS', 'https://madenimura-journal.kz/index.php/main/oai', 'oai_pmh', 'Археология, этнология, тарих, музей ісі', 2, '09.12.2025 ж. №2138 бұйрық', '2025 жылғы қазан айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Нефть и газ', 'ҚР Білім және ғылым министрлігі Ұлттық ғылымдар академиясы', 'https://neft-gas.kz/kontakty', null, null, 'manual', 'Геология, мұнайхимия, бұрғылау, өндіру, барлау салалары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2022 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Отан тарихы', 'Ш. Уәлиханов атындағы Тарих және этнология институты', 'https://www.otan.history.iie.kz/main', 'OJS', 'https://www.otan.history.iie.kz/main/oai', 'oai_pmh', 'Тарих ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Педагогика және психология', 'Абай атындағы Қазақ ұлттық педагогика университеті', 'https://journal-pedpsy.kaznpu.kz/index.php/ped', 'OJS', 'https://journal-pedpsy.kaznpu.kz/index.php/ped/oai', 'oai_pmh', 'Педагогика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Проблемы агрорынка', 'Қазақ аграрлық-өнеркәсіптік кешенінің экономикасы және ауылдық аумақтарды дамыту ғылыми-зерттеу институты', 'https://kazagroeconom.kz/ru/scientific-3/journal', null, null, 'manual', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Статистика, учет и аудит', 'Алматы гуманитарлы-экономикалық университеті', 'https://sua.aesa.kz/main/about', 'OJS', 'https://sua.aesa.kz/index.php/main/oai', 'oai_pmh', 'Экономика', 2, '12.07.2024 ж. № 603 бұйрық', '2024 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Теориялық және клиникалық медицинаның өзекті мәселелері', 'Қазақстан-Ресей медициналық университеті', 'https://kazrosmedjournal.krmu.edu.kz/', 'Elpub', 'https://kazrosmedjournal.krmu.edu.kz/jour/oai', 'oai_pmh', 'Медицина ғылымдары', 2, '22.11.2024 ж. № 1097 бұйрық', '2025 жылғы қаңтар айынан бастап', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Топырақтану және агрохимия', 'О.О.Оспанов атындағы Қазақ топырақтану және агрохимия ғылыми-зерттеу институты', 'https://journal.soil.kz/jour?locale=ru_RU', 'Elpub', 'https://journal.soil.kz/jour/oai', 'oai_pmh', 'Ауыл шаруашылығы ғылымдары -Топырақ географиясы, Топырақ құнарлылығы, Топырақ биологиясы, Топырақ экологиясы', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2023 жыл', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Торайғыров университетінің хабаршысы', 'Торайғыров университеті', 'https://vestnik.tou.edu.kz/', null, null, 'manual', 'Педагогикалық сериясы', 2, '12.07.2024 ж. № 603 бұйрық', '2021 жылғы наурыз – 2023 жылғы маусым аралығында және 2024 жылғы шілде айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Торайғыров университетінің хабаршысы. Физика, математика және компьютерлік ғылымдар сериясы', 'Торайғыров университеті', 'https://vestnik-pm.tou.edu.kz/', null, null, 'manual', 'Физика ғылымдары', 2, '20.08.2024 ж. № 740 бұйрық', '2024 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Торайғыров университетінің хабаршысы. Филология сериясы', 'Торайғыров университеті', 'https://vestnik-philological.tou.edu.kz/', null, null, 'manual', 'Филология ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Торайғыров университетінің хабаршысы. Экономикалық серия', 'Торайғыров университеті', 'https://vestnik-economic.tou.edu.kz/archive/journals', null, null, 'manual', 'Экономика және бизнес', 2, '12.07.2024 ж. № 603 бұйрық', 'шілде 2023 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Торайғыров университетінің хабаршысы. Энергетикалық сериясы', 'Торайғыров университеті', 'https://vestnik-energy.tou.edu.kz/', null, null, 'manual', 'Энергетика', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2022 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Тіл және әдебиет: теориясы мен тәжірибесі – Язык и литература: теория и практика', 'Әлкей Марғұлан атындағы Павлодар педагогикалық университеті', 'https://yazlit.ppu.edu.kz/index.php/new/index', 'OJS', 'https://yazlit.ppu.edu.kz/index.php/new/oai', 'oai_pmh', 'Филология', 2, '12.07.2024 ж. № 603 бұйрық', '2024 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Университет еңбектері - Труды Университета', 'Әбілқас Сағынов атындағы Қарағанды техникалық университеті', 'https://tu.kstu.kz/about', null, null, 'manual', 'Машинажасау, Энергетика және автоматика, Ақпараттық-коммуникациялық технологиялар', 2, '12.07.2024 ж. № 603 бұйрық', '2021 жылғы маусым айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Фтизиопульмонология', 'Қазақстан Республикасы Фтизиопульмонология ұлттық ғылыми орталығы', 'https://journal.nncf.kz/', null, null, 'manual', 'Медицина ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'шілде 2023 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Халықаралық ақпараттық және коммуникациялық технологиялар журналы', 'Халықаралық ақпараттық технологиялар университеті', 'https://journal.iitu.edu.kz/index.php/ijict/about-journals', 'OJS', 'https://journal.iitu.edu.kz/index.php/ijict/oai', 'oai_pmh', 'Информатика', 2, '28.02.2025 ж. №293 бұйрық', '2025 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Ш.Уәлиханов атындағы Көкшетау университетінің хабаршысы. Филология сериясы', 'Ш.Уәлиханов атындағы Көкшетау университеті', 'https://vestnik.kgu.kz/index.php/kufil/about', 'OJS', 'https://vestnik.kgu.kz/index.php/kufil/oai', 'oai_pmh', 'Филология ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Шәкәрім университетінің хабаршысы. Техникалық ғылымдар сериясы', '«Шәкәрім университеті» коммерциялық емес акционерлік қоғамы', 'https://shakarim.university/kz/science/journals/tech', null, null, 'manual', 'Химиялық технология, тамақ инженериясы және биотехнология', 2, '12.07.2024 ж. № 603 бұйрық', '2023 жылғы қазан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Ғылым және денсаулық сақтау (Наука и здравоохранение)', 'Cемей медицина университеті', 'https://smu.edu.kz/ru/nauka/zhurnal-nauka-i-zdravoohranenie/', null, null, 'manual', 'Медицина ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('ҚР ҰЯО жаршысы. Вестник НЯЦ РК', 'Қазақстан Республикасы Ұлттық ядролық орталығы', 'https://www.nnc.kz/publications/bulletin.html', null, null, 'manual', 'Физикалық ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'шілде 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('ҚазТБУ Хабаршысы', 'Қазақ технология және бизнес университеті', 'https://vestnik.kaztbu.edu.kz/index.php/kazutb/about/contact', 'OJS', 'https://vestnik.kaztbu.edu.kz/index.php/kazutb/oai', 'oai_pmh', 'Тау-кен ісі және мұнай-газ ісі', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2023 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қазақ бас сәулет-құрылыс академиясының Хабаршысы', 'Халықаралық білім беру корпорациясы', 'https://vestnik.kazgasa.kz/kz', null, null, 'manual', 'Сәулет және құрылыс саласы', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қазақ экономика, қаржы және халықаралық сауда университетінің жаршысы', 'Қазақ экономика, қаржы және халықаралық сауда университеті', 'https://vestnik.kuef.kz/', null, null, 'manual', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: <urlopen error timed out>).'),
  ('Қазақстан Республикасы Заңнама және құқықтық ақпарат институтының жаршысы', 'ҚР ӘМ Қазақстан Республикасының Заңнама және құқықтық ақпарат институты', 'https://vestnik.zqai.kz/index.php/vestnik/index', 'OJS', 'https://vestnik.zqai.kz/index.php/vestnik/oai', 'oai_pmh', 'Заң ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қазақстан Республикасының ұлттық инженерлік академиясының хабаршысы', 'Қазақстан Республикасының ұлттық инженерлік академиясы', 'https://journal.neark.kz/kk/kontakty/', null, null, 'manual', 'Математика ғылымдары, ақпараттық-коммуникациялық технологиялар', 2, '12.07.2024 ж. № 603 бұйрық', 'мамыр 2021 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: HTTP 403).'),
  ('Қазақстан клиникалық медицинасы - Journal of clinical medicine of Kazakhstan', 'Ұлттық ғылыми-медицина орталығы', 'https://www.clinmedkaz.org/home/Publisher', null, null, 'manual', 'Медицина ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық 18.01.2025 ж. № 186 бұйрық', 'ақпан 2021 жыл-желтоқсан 2024 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қазақстан хирургиясының хабаршысы', 'А.Н. Сызганов атындағы Ұлттық ғылыми хирургия орталығы', 'https://vhk.kz/kk/editorial/', 'OJS', 'https://vhk.kz/index.php/index/oai', 'oai_pmh', 'Медицина', 2, '12.07.2024 ж. № 603 бұйрық', 'қазан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қазақстан ғылымы мен техникасы', 'Торайғыров университеті', 'https://stk.tou.edu.kz/public/', null, null, 'manual', 'Металлургия, Машина жасау, көлік', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2023 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қазақстан-Спектр', 'ҚР Президенті жанындағы Қазақстан стратегиялық зерттеулер институты', 'https://journal-ks.kisi.kz/', 'OJS', 'https://journal-ks.kisi.kz/index.php/ks/oai', 'oai_pmh', 'Саясаттану', 2, '12.07.2024 ж. № 603 бұйрық', 'қыркүйек 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қазақстанның жоғары мектебі', 'Жоғары білім беруді дамыту ұлттық орталығы', 'https://highedujournal.kz/index.php/1', 'OJS', 'https://highedujournal.kz/index.php/1/oai', 'oai_pmh', 'Педагогикалық ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'сәуір 2024 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қазақстанның кен журналы. Горный журнал Казахстана', 'Научно-производственное предприятие «Интеррин»»', 'https://minmag.kz/ru/%D0%BA%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D1%8B/', null, null, 'manual', 'Жер туралы ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2022 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қазақстанның мұнай-газ саласының хабаршысы', 'КМГ Инжиниринг', 'https://vestnik-ngo.kz/2707-4226/index/index/kk_KZ', 'OJS', 'https://vestnik-ngo.kz/2707-4226/oai', 'oai_pmh', 'Мұнай және газ', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2022 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қазақстанның онкологиясы мен радиологиясы', 'Қазақ онкология және радиология ғылыми-зерттеу институты', 'https://ojs.oncojournal.kz/index.php/oncol-and-radiol-of-kazakhstan/issue/download/13/9', 'OJS', 'https://ojs.oncojournal.kz/index.php/oncol-and-radiol-of-kazakhstan/oai', 'oai_pmh', 'Медицина ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қараша 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қазақстанның педагогикалық хабаршысы', 'Әлкей Марғұлан атындағы Павлодар педагогикалық университеті', 'https://pedvestnik.ppu.edu.kz/index.php/new/about', 'OJS', 'https://pedvestnik.ppu.edu.kz/index.php/new/oai', 'oai_pmh', 'Білім беру және педагогтық зерртеулер', 2, '09.12.2025 ж. №2138 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қазақстанның химия журналы -Химический журнал Казахстана', 'Ә.Б.Бектуров атындағы Химия ғылымдары институты', 'https://www.chemjournal.kz/index.php/journal', 'OJS', 'https://www.chemjournal.kz/index.php/journal/oai', 'oai_pmh', 'Химия ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'желтоқсан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰМУ хабаршысы', 'С.Д.Асфендияров атындағы Қазақ ұлттық медицина университеті', 'https://vestnik.kaznmu.edu.kz/kaz/index.php', null, null, 'manual', 'Медицина ғылымдары', 2, '18.07.2025 ж. №1219 бұйрық', '2025 жылғы шілде айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('ҚазҰУ Хабаршысы. Дінтану сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-religious.kaznu.kz/index.php/relig/about/index', 'OJS', 'https://bulletin-religious.kaznu.kz/index.php/relig/oai', 'oai_pmh', 'Дінтану және исламтану ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ Хабаршысы. Философия, мәдениеттану, саясаттану сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-philospolit.kaznu.kz/index.php/1-pol/ru/issue/view/20', 'OJS', 'https://bulletin-philospolit.kaznu.kz/index.php/1-pol/oai', 'oai_pmh', 'Философия, мәдениеттану, саясаттану', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Биология сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bb.kaznu.kz/index.php/biology/kk', 'OJS', 'https://bb.kaznu.kz/index.php/biology/oai', 'oai_pmh', 'Биологиялық ғылымдар', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. География сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-geography.kaznu.kz/index.php/1-geo/about', 'OJS', 'https://bulletin-geography.kaznu.kz/index.php/1-geo/oai', 'oai_pmh', 'География ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Заң сериясы Вестник КазНУ. Серия юридическая', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-law.kaznu.kz/index.php/journal/kk/issue/archive', 'OJS', 'https://bulletin-law.kaznu.kz/index.php/journal/oai', 'oai_pmh', 'Заң ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Педагогикалық ғылымдар сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-pedagogic-sc.kaznu.kz/index.php/1-ped/ru', 'OJS', 'https://bulletin-pedagogic-sc.kaznu.kz/index.php/1-ped/oai', 'oai_pmh', 'Педагогика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Психология және социология сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-psysoc.kaznu.kz/index.php/1-psy/kk/announcement', 'OJS', 'https://bulletin-psysoc.kaznu.kz/index.php/1-psy/oai', 'oai_pmh', 'Психология және социология ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Тарих сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-history.kaznu.kz/', 'OJS', 'https://bulletin-history.kaznu.kz/index.php/index/oai', 'oai_pmh', 'Тарих ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Филология сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://philart.kaznu.kz/index.php/1-FIL/kk', 'OJS', 'https://philart.kaznu.kz/index.php/1-FIL/oai', 'oai_pmh', 'Тілтану және әдебиеттану', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Халықаралық қатынастар және халықаралық құқық сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-ir-law.kaznu.kz/index.php/1-mo/kk/issue/archive', 'OJS', 'https://bulletin-ir-law.kaznu.kz/index.php/1-mo/oai', 'oai_pmh', 'Халықаралық қатынастар', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Шығыстану сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-orientalism.kaznu.kz/index.php/1-vostok/ru', 'OJS', 'https://bulletin-orientalism.kaznu.kz/index.php/1-vostok/oai', 'oai_pmh', 'Шығыстану', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Экология сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://bulletin-ecology.kaznu.kz/index.php/1-eco/kk/index', 'OJS', 'https://bulletin-ecology.kaznu.kz/index.php/1-eco/oai', 'oai_pmh', 'Экология', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('ҚазҰУ хабаршысы. Экономика сериясы', 'әл-Фараби атындағы Қазақ ұлттық университеті', 'https://be.kaznu.kz/index.php/math/kk/announcement', 'OJS', 'https://be.kaznu.kz/index.php/math/oai', 'oai_pmh', 'Экономика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'ақпан 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қарағанды университетінің хабаршысы. Педагогика сериясы', 'Академик Е.А. Бөкетов атындағы Қарағанды университеті', 'https://pedagogy-vestnik.buketov.edu.kz/pedagogy-vestnik', 'OJS', 'https://pedagogy-vestnik.buketov.edu.kz/index.php/pedagogy-vestnik/oai', 'oai_pmh', 'Педагогика ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қарағанды университетінің хабаршысы. Құқық сериясы', 'Академик Е.А. Бөкетов атындағы Қарағанды университеті', 'https://law-vestnik.buketov.edu.kz/', 'OJS', 'https://law-vestnik.buketov.edu.kz/index.php/index/oai', 'oai_pmh', 'Заң ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Қоркыт Ата атындағы Қызылорда университетінің Хабаршысы', 'Қоркыт Ата атындағы Қызылорда университеті', 'https://www.korkyt.kz/kz/', null, null, 'manual', 'Ауыл шаруашылығы ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'қаңтар 2022 жыл', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қоғам және дәуір', 'Қазақстан Республикасының Президенті жанындағы Қазақстан стратегиялық зерттеулер институты', 'https://www.journal-kogam.kisi.kz/index.php/kd/index', 'OJS', 'https://www.journal-kogam.kisi.kz/index.php/kd/oai', 'oai_pmh', 'Саяси ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'маусым 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Құқық және мемлекет', 'M.S. Narıkbaev atyndağy KAZGUU Unıversıteti', 'https://km.mnu.kz/pdf/release/%D0%9F%D1%80%D0%B0%D0%B2%D0%BE%20%D0%B8%20%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%BE%20%E2%84%962%2871%29%2C%202016.pdf', null, null, 'manual', 'Құқық', 2, '21.11.2024 ж. № 1087 бұйрық', '2024 жылғы шілде айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Әл-Фараби', 'Философия, саясаттану және дінтану институты', 'https://alfarabijournal.org/index.php/journal', 'OJS', 'https://alfarabijournal.org/index.php/journal/oai', 'oai_pmh', 'Философия ғылымдары', 2, '12.07.2024 ж. № 603 бұйрық', 'наурыз 2021 жыл', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Өрлеу. Үздіксіз білім жаршысы', '«Өрлеу» біліктілікті арттыру ұлттық орталығы» АҚ', 'https://journal.orleu-edu.kz/index.php/vesti-no', 'OJS', 'https://journal.orleu-edu.kz/index.php/vesti-no/oai', 'oai_pmh', 'Білім беру және педагогикалық зерттеулер', 2, '23.01.2025 ж. № 47 бұйрық', '2024 жылғы қазан айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Epidemiology&Health Data Insights', 'Australasia Publishing Group', 'https://www.journalehdi.com/', 'OJS', 'https://www.journalehdi.com/oai', 'oai_pmh', 'Эпидемиология және денсаулық сақтау саласындағы деректерді талдау', 3, '18.04.2026 ж. № 282 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Hikmet', '«Қожа Ахмет Ясауи атындағы Халықаралық Қазақ-Түрік университеті» мекемесі', 'https://journals.ayu.edu.kz/index.php/hikmet/about', 'OJS', 'https://journals.ayu.edu.kz/index.php/hikmet/oai', 'oai_pmh', 'Дінтану, исламтану', 3, '12.08.2026 ж. № 589 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Journal of Ecology and Sustainability', 'Л.Н. Гумилев атындағы Еуразия ұлттық университеті', 'https://jes.enu.kz/index.php/jes/info', 'OJS', 'https://jes.enu.kz/index.php/jes/oai', 'oai_pmh', 'Экологиялық инжиниринг', 3, '07.03.2025 ж. № 361 бұйрық 13.02.2026 ж. № 117 бұйрық', '2025 жылғы №1 нөмірінен бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('QAZAQTANU', 'М.Әуезов атындағы Оңтүстік Қазақстан университеті', 'https://qazaqtany.auezov.edu.kz/index.php/qazaqtany/about', 'OJS', 'https://qazaqtany.auezov.edu.kz/index.php/qazaqtany/oai', 'oai_pmh', 'Қазақстан тарихы, жалпы тарих, өлкетану', 3, '21.04.2026 ж. № 300 бұйрық', '2026 жылғы шілде айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Technobius Physics', '«Technobius» ЖШС', 'https://technobius.kz/index.php/phys', 'OJS', 'https://technobius.kz/index.php/phys/oai', 'oai_pmh', 'Физикалық ғылымдар', 3, '27.11.2025 ж. № 2106 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('«Сот төрелігі академиясының хабаршысы»', 'Қазақстан Республикасы Жоғары сот кеңесінің жанындағы Сот төрелігі академиясы', 'https://vestnik.sta-jsk.kz/index.php/jsk', 'OJS', 'https://vestnik.sta-jsk.kz/index.php/jsk/oai', 'oai_pmh', 'Заң ғылымдары', 3, '14.07.2025 ж. № 1187 бұйрық', '2025 жылғы сәуір айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Ілияс Жансүгіров атындағы Жетісу мемлекеттік университетінің Хабаршысы', 'Ілияс Жансүгіров атындағы Жетісу мемлекеттік университеті', 'https://journal.zhetysu.edu.kz/index.php/home/index', 'OJS', 'https://journal.zhetysu.edu.kz/index.php/home/oai', 'oai_pmh', 'Педагогика ғылымдары', 3, '19.06.2025 ж. № 938 бұйрық', '2025 жылғы №2 нөмірінен бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Абай атындағы ҚазҰПУ хабаршысы. Юриспруденция сериясы', '«Абай атындағы Қазақ ұлттық педагогикалық университеті» КеАҚ', 'https://bulletin-jurisprudence-kaznpu.kz/index.php/home', 'OJS', 'https://bulletin-jurisprudence-kaznpu.kz/index.php/home/oai', 'oai_pmh', 'Құқық', 3, '14.08.2026 ж. № 600 бұйрық', '2026 жылғы қаңтар айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('БҚУ Хабаршысы', 'М.Өтемісов атындағы Батыс Қазақстан университеті', 'https://joba.wku.edu.kz/index.php/kk/gylym/gylymy-baspa/khabarjy', null, null, 'manual', 'Тарих ғылымдары', 3, '22.10.2024 ж. № 900 бұйрық', '2024 жылғы №3 нөмірінен бастап', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: HTTP 404).'),
  ('М.Қозыбаев атындағы Солтүстік Қазақстан университетінің Хабаршысы', 'М. Қозыбаев атындағы Солтүстік Қазақстан университеті', 'https://vestnik.ku.edu.kz/jour/about/history?locale=ru_RU', 'Elpub', 'https://vestnik.ku.edu.kz/jour/oai', 'oai_pmh', 'Биология ғылымдары', 3, '23.01.2026 ж. № 34 бұйрық', '2026 жылғы қаңтар айынан бастап', true, 'OAI-PMH найден и проверен автоматически 2026-10-09. Сайт отвечает только браузерному User-Agent.'),
  ('Педагогикалық өлшемдер – Педагогические измерения', 'Қазақстан Республикасының Ғылым және жоғары білім министрлігі «Ұлттық тестілеу орталығы» Шаруашылық жүргізу құқығындағы Республикалық мемлекеттік кәсіпорын', 'https://testcenter-zhurnal.kz/', 'OJS', 'https://testcenter-zhurnal.kz/index.php/sap/oai', 'oai_pmh', 'Педагогикалық өлшемдер, білім беру сапасын басқару', 3, '17.06.2026 ж. №482 бұйрық', '2026 жылғы сәуір айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Торайғыров университетінің хабаршысы. Гуманитарлық сериясы', 'Toraighyrov University', 'https://vestnik-humanitar.tou.edu.kz/', null, null, 'manual', 'Философия', 3, '19.09.2025 ж. №1605 бұйрық', '2025 жылғы қыркүйек айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Туризм, демалыс және қонақжайлылық', 'Қазақ спорт және туризм академиясы', 'https://tlh.kz/', null, null, 'manual', 'Туризм, Қонақжайлылық', 3, '10.12.2024 ж. № 1153 бұйрық', '2024 жылғы №3 (6) нөмірінен бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Түркология', 'Қожа Ахмет Ясауи атындағы Халықаралық қазақ-түрік университеті', 'https://dergipark.org.tr/tr/pub/ayt/issue/105520', null, null, 'manual', 'Филология ғылымдары', 3, '30.12.2025 ж. № 2169 бұйрық', '2025 жылғы қазан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қ. Жұбанов атындағы Ақтөбе өңірлік университетінің хабаршысы', '«Қ. Жұбанов атындағы Ақтөбе өңірлік университеті» коммерциялық емес акционерлік қоғамы', 'https://zhubanov.edu.kz/kk/science/category/95/', null, null, 'manual', 'Компьютерлік ғылымдар және ақпараттық технологиялар', 3, '16.07.2026 ж. № 557 бұйрық', '2026 жылғы сәуір айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қазақстан шығыстануы', 'Р.Б. Сүлейменов атындағы Шығыстану институты', 'https://journal.shygystanu.kz/index.php/main/payment', 'OJS', 'https://journal.shygystanu.kz/index.php/main/oai', 'oai_pmh', 'Шығыстану ғылымдары', 3, '22.08.2024 ж. №767 бұйрық', '2024 жылғы №3 нөмірінен бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Азаматтық қорғаудағы ғылым мен білім', 'Қазақстан Республикасы Төтенше жағдайлары министрлігі Мәлік Ғабдуллин атындағы Азаматтық қорғау академиясы', 'https://agz.edu.kz/121.html', null, null, 'manual', 'Техникалық ғылымдар', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2023 жыл маусым айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Бағдар-Ориентир', 'Қазақстан Республикасының Ұлттық қорғаныс университеті', 'https://bagdar-orientir.kz/ru/', null, null, 'manual', 'Ұлттық қауіпсіздік және әскери іс', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2021 жыл ақпан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('РЭжБӘИИ ғылыми еңбектері – Научные труды ВИИРЭиС', 'Қазақстан Республикасының Қорғаныс министрлігінің Радиоэлектроника және байланыс әскери-инженерлік институты', 'https://viires.edu.kz/cms/uploads/files/%D0%9D%D0%B0%D1%83%D1%87%D0%BD%D1%8B%D0%B5%20%D1%82%D1%80%D1%83%D0%B4%D1%8B%20%D0%92%D0%98%D0%98%D0%A0%D0%AD%D0%B8%D0%A1%20%E2%84%961.pdf.pdf', null, null, 'manual', 'Ұлттық қауіпсіздік және әскери іс', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2021 жыл ақпан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: <urlopen error [Errno 11002] getaddrinfo failed>).'),
  ('С. Нұрмағамбетов атындағы ҚӘӘИ хабаршысы – Вестник ВИСВ имени С.Нурмагамбетова', 'Қазақстан Республикасы Қорғаныс министрлігінің С. Нұрмағамбетов атындағы Құрлық әскерлерінің Әскери институты', 'https://journal-visv.kz/index.php/visv', 'OJS', 'https://journal-visv.kz/index.php/visv/oai', 'oai_pmh', 'Әскери іс', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2023 жыл сәуір айынан бастап', false, 'OAI-PMH найден и проверен автоматически 2026-10-09.'),
  ('Сардар', 'Әскери стратегиялық зерттеулер орталығы', 'https://sardar.qalam-masters.kz/ru/policy', null, null, 'manual', 'Әскери іс', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2023 жыл маусым айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Хабаршы-Вестник', 'Қазақстан Республикасының Ішкі істер министрлігінің Б.Бейсенов атындағы Қарағанды академиясы', 'https://kpa.edu.kz/category/9-nauka-kz/9-4-o-zhurnale-habarshi-vestnik-kz/journal-kz/', null, null, 'manual', 'Құқық қорғау қызметі', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2021 жыл ақпан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Хабаршысы – Вестник', 'Қазақстан Республикасының Ұлттық қорғаныс университеті', 'https://habarshy.kz/ru/', null, null, 'manual', 'Ұлттық қауіпсіздік және әскери іс', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2021 жыл ақпан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Ғылым-Наука', 'Қазақстан Республикасы Ішкі істер министрлігінің Шырақбек Қабылбаев атындағы Қостанай академиясы', 'https://qpa.edu.kz/journal-science', null, null, 'manual', 'Құқық қорғау қызметі', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2021 жыл ақпан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қазақстан Республикасы Ұлттық ұлан академиясының хабаршысы – Вестник Академии национальной гвардии Республики Казахстан', 'Қазақстан Республикасы Ұлттық ұлан академиясы', 'https://www.ang.edu.kz/rus/wp-content/uploads/2024/04/%D0%92%D0%B5%D1%81%D1%82%D0%BD%D0%B8%D0%BA-%D0%90%D0%9D%D0%93-%D0%A0%D0%9A-%E2%84%964-51-2024.pdf', null, null, 'manual', 'Әскери іс', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2021 жыл ақпан айы айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Қазақстан Республикасының ІІМ Мақан Есболатов атындағы Алматы академиясының ғылыми еңбектері – Ученые труды Алматинской академии МВД Республики Казахстан имени Макана Есбулатова', 'Қазақстан Республикасының Ішкі істер министрлігінің Мақан Есболатов атындағы Алматы академиясы', 'https://alpolac.edu.kz/ru/o-zhurnale/', null, null, 'manual', 'Құқық қорғау қызметі', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2021 жыл ақпан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09.'),
  ('Құқық қорғау органдары академиясының Жаршысы – Вестник Академии правоохранительных органов', 'Қазақстан Республикасы Бас прокуратурасының жанындағы Құқық қорғау органдары академиясы', 'https://vestnikacademy.kz/?lang=ru&page_id=1439', null, null, 'manual', 'Құқық қорғау қызметі', 4, '12.07.2024 ж. № 603 бұйрық, 08.09.2025 ж. № 1531 бұйрық', '2021 жыл ақпан айынан бастап', false, 'OAI-PMH не найден автоматически 2026-10-09 (сайт: HTTP 403).')
) as v(name, publisher, base_url, platform, oai_endpoint, crawler_type, discipline,
       koksnvo_list, koksnvo_order, koksnvo_included_from, oai_browser_user_agent, notes)
where not exists (
  select 1 from journals j
  where j.base_url = v.base_url or (v.oai_endpoint is not null and j.oai_endpoint = v.oai_endpoint)
);

-- Профиль журнала: + ошибка харвеста и дата включения в перечень.
drop function if exists journal_profiles();

create function journal_profiles()
returns table (
  id uuid,
  name text,
  publisher text,
  base_url text,
  platform text,
  oai_endpoint text,
  issn_print text,
  issn_online text,
  language text,
  open_access boolean,
  discipline text,
  source_type text,
  koksnvo_list smallint,
  koksnvo_order text,
  koksnvo_included_from text,
  last_crawled_at timestamptz,
  harvest_error text,
  article_count bigint
)
language sql stable
as $$
  select
    j.id, j.name, j.publisher, j.base_url, j.platform, j.oai_endpoint,
    j.issn_print, j.issn_online, j.language, j.open_access, j.discipline,
    j.source_type, j.koksnvo_list, j.koksnvo_order, j.koksnvo_included_from,
    j.last_crawled_at, j.harvest_error,
    count(a.id) as article_count
  from journals j
  left join articles a on a.journal_id = j.id
  group by j.id
  order by count(a.id) desc, j.name;
$$;

-- Поиск: фильтры по журналу и списку КОКСНВО теперь на сервере. Раньше фронтенд
-- фильтровал топ-40 на клиенте — при ~200 журналах это почти всегда давало пустую выдачу.
drop function if exists search_articles(text, int);

create function search_articles(
  query text,
  limit_count int default 20,
  journal_filter uuid default null,
  koksnvo_filter smallint default null
)
returns table (
  id uuid,
  journal_id uuid,
  journal_name text,
  title text,
  authors text,
  abstract text,
  doi text,
  publication_date date,
  volume text,
  issue text,
  pages text,
  language text,
  article_url text,
  pdf_url text,
  metadata_quality text,
  cited_by_count int,
  cited_by_scopus_count int,
  citing_works jsonb,
  rank real
)
language sql stable
as $$
  select
    a.id,
    a.journal_id,
    j.name as journal_name,
    a.title,
    a.authors,
    a.abstract,
    a.doi,
    a.publication_date,
    a.volume,
    a.issue,
    a.pages,
    a.language,
    a.article_url,
    a.pdf_url,
    a.metadata_quality,
    a.cited_by_count,
    a.cited_by_scopus_count,
    a.citing_works,
    ts_rank(a.search_vector, websearch_to_tsquery('russian', query)) as rank
  from articles a
  join journals j on j.id = a.journal_id
  where a.search_vector @@ websearch_to_tsquery('russian', query)
    and (journal_filter is null or a.journal_id = journal_filter)
    and (koksnvo_filter is null or j.koksnvo_list = koksnvo_filter)
  order by rank desc
  limit limit_count;
$$;
